resources:
  - name: repo
    type: git
    source: 
      uri: https://github.com/Naveen-GDTC/repo
      branch: main


jobs:
  - name: read-secret
    plan:
      - get: repo
      - task: show-secret
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: hashicorp/vault
          outputs:
            - name: credentials
          run:
            path: sh
            args:
              - -c
              - |
                # Shell script to fetch credentials from Vault
                export VAULT_ADDR='http://192.168.1.223:8200'
                export VAULT_TOKEN='token'
 
                # Fetch credentials from Vault
                USERNAME=$(vault kv get -field=username secret/cred)
                PASSWORD=$(vault kv get -field=password secret/cred)
                HOST_IP=$(vault kv get -field=host_ip secret/cred)
                STOCK_CODE=$(vault kv get -field=stock_code secret/cred)
                
 
                # Store credentials in a file
                echo $USERNAME > credentials/username.txt
                echo $PASSWORD > credentials/password.txt
                echo $HOST_IP > credentials/host.txt
                echo $STOCK_CODE > credentials/stock_code.txt


      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: python
              tag: "3.9"
          inputs:
            - name: credentials 
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                # Installing required libraries
                pip install bs4 
                pip install pandas
                pip install requests
                pip install psycopg2 

                # Read credentials from files
                export STOCK_CODE=$(cat credentials/stock_code.txt)
                export USERNAME=$(cat credentials/username.txt)
                export PASSWORD=$(cat credentials/password.txt)
                export HOST_IP=$(cat credentials/host.txt)

                echo "USERNAME: $USERNAME"
                echo "PASSWORD: $PASSWORD"
                echo "HOST_IP: $HOST_IP"
                echo "STOCK_CODE: $STOCK_CODE"
 
                python3 repo/script.py
