resources:
  - name: repo
    type: git
    source: 
      uri: https://github.com/Naveen-GDTC/repo
      branch: main


jobs:
  - name: read-secret
    plan:
      - get: repo
      - task: show-secret
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: hashicorp/vault
          outputs:
            - name: credentials # Store output in a folder
          run:
            path: sh
            args:
              - -c
              - |
                # Shell script to fetch credentials from Vault
                export VAULT_ADDR='http://192.168.1.223:8200'
                export VAULT_TOKEN='hvs.Xu2NTlVFcMSQeYeAEIToorWL'
 
                # Fetch credentials from Vault
                USERNAME=$(vault kv get -field=username secret/cred)
                PASSWORD=$(vault kv get -field=password secret/cred)
 
                # Store credentials in a file
                echo $USERNAME > credentials/username.txt
                echo $PASSWORD > credentials/password.txt

  - name: run-python-script
    plan:
      # - get: credentials # Fetch the output of the previous job
        # trigger: true
      
      - get: repo
        trigger: true

      - task: run-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: python
              tag: "3.9"
          inputs:
            # - name: credentials # Input the credentials from the previous job
            - name: repo
          run:
            path: sh
            args:
              - -c
              - |
                # Install required libraries
                pip install bs4 
                pip install pandas
                pip install requests
                pip install psycopg2
                pip install SQLAlchemy 

                # Read credentials from files
                USERNAME=$(cat credentials/username.txt)
                PASSWORD=$(cat credentials/password.txt)
 
                python3 repo/script.py
